name: Publish Signed APK

on:
  push:
    tags:
      - "v*.*.*"
      
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: assembleRelease
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
          keyStorePassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyPassword: ${{ secrets.SIGNING_KEY_ALIAS_PASSWORD }}
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: ${{ steps.sign.outputs.signedReleaseFile }}
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.sign.outputs.signedReleaseFile }}
          draft: true
          token: ${{ secrets.RELEASE_TOKEN }}
          generate_release_notes: true

